### ISSUE TITLE
offline & online events received on destroyed instance

### ISSUE THREAD

**Issue by wizcorp-olivier** [primus/primus#399] opened 2015-10-01 10:11 UTC
Hello and thanks a lot for Primus!

I thing I am having an issue with Primus.open => I receive the "open" event but the connection seems to be closed:
- ```this.readyState``` is ```Primus.CLOSED``` (value 2 instead of 3)
- At the same time, ```this.readable``` and ```this.writable``` are also ```false``` (not surprising).

Current readme.md says:
- "Be sure to use primus.open() correctly, see below for details."
- "When you call primus.open() you should make sure that the connection is totally dead (e.g. after an end event) and primus isn't already trying or planning to reconnect."

My questions are:
- Is there a way for Primus.open to refuse / give an error if a dupe connection is about to be made?
- Could we improve the documentation to explain how to avoid calling "open" on a "non totally dead" connection? I.e. is a check like below enough to fix my issue:
```js
if (primus.readyState === Primus.CLOSED) {
    primus.open();
}
```
NB: it looks like the test above is not enough because Primus might be trying to reconnect at the same time. Is there a simple way to verify this too?

**Comment by 3rd-Eden** [comment] 2015-10-01 11:40
That is a really odd issue, when I look at the source (https://github.com/primus/primus/blob/master/primus.js#L398-L443) you'll see that readable, writable are set to `true` and that the readyState will be set to OPEN before the `open` even is emitted. 

Is there any way to reproduce this?

**Comment by lpinca** [comment] 2015-10-01 14:07
@wizcorp-olivier regarding your questions:

1. No, right now there isn't anything like that.
2. You should also check if primus is reconnecting:

  ```js
    if (primus.readyState === Primus.CLOSED && !primus.recovery.reconnecting()) {
      primus.open();
    }
  ```

**Comment by wizcorp-olivier** [comment] 2015-10-02 08:26
Thank you @lpinca for the sample, I added this to my code.

After more investigation, here is more info (this gave me a workaround too, actually):
1 - We are creating a Primus instance #1 as below:
```JS
primus = new Primus(url, {
		manual: true,
		strategy: 'disconnect,timeout', // disabled 'online'
		reconnect: { max: 5000, min: 500, retries: 10 }
});```
2 - We use this connection fine for a while, then close this connection by calling primus.end()
3 - We create another instance #2 (calling ```new Primus(...)```) with similar parameters (same URL for now but it will be 2 separate URLs in the future).
4 - At some point (depending on our network), we get a "WebSocket network error: The operation couldn't be completed. Socket is not connected"
5 - Following this error we see events: ```reconnect scheduled```, ```offline```, ```end```, and finally ```online```.
6 - Inside the ```online``` event, I noticed that the Primus object given in ```this``` is the instance #1 (instead of instance #2).
7 - Since our code was keeping a variable "primus", my workaround was to update this variable (```primus = this```) in the online event. I also put it in the "open" event to be safe.

Does it explain our issue better - and maybe what we are doing wrong?

**Comment by lpinca** [comment] 2015-10-02 09:52
It sounds like you are using a reference to the wrong instance.
Can you use us how you create the two instance and attach the event listeners?

**Comment by wizcorp-olivier** [comment] 2015-10-02 10:49
Well in short, after the error + offline/online Primus seems to be triggering the event on the "previous" (# 1) instance. Not sure why... here is the code.
Sorry for the big piece of code... Just trying to minimize the round trips in this conversation.
```JS
var EventEmitter = require('events').EventEmitter;


exports = module.exports = new EventEmitter();

var primus;

var isReconnect;
var wantConnection; // false when we disconnect voluntarily, give up attempts, or never tried yet
var online;
var voluntarilyClosed;
var uniqueId = 0;


exports.connect = function (url) {
	if (primus) {
		console.error('connect: destroying old Primus:', primus);
		// destroy only emits "destroy" and nothing else
		primus.destroy();
		primus = null;

		return setTimeout(function () {
			exports.connect(url);
		}, 0);
	}

	var Primus = window.Primus;

	// reset state variables

	voluntarilyClosed = false;
	wantConnection = true;
	isReconnect = false;
	online = true;

	primus = new Primus(url, {
		// 'manual' means we need to call 'open()' to start our connection
		manual: true,
		// Reconnect strategy: disabled default 'online' because Primus would try even when we don't want to
		strategy: 'disconnect,timeout',
		reconnect: {
			max: 5000, // The maximum delay before we try to reconnect. (ms)
			min: 500,  // The minimum delay before we try reconnect. (ms)
			retries: 10 // How many times we should try to reconnect
		}
	});
	primus.myID = ++uniqueId;
	console.error('connect: creating new Primus:', primus, 'with ID:', uniqueId, 'URL:', url);

	/**
	 * We emit 'open' each time we connect or reconnect.
	 *  NB: in case of reconnection, Primus sends 'open' then 'reconnected'; we only care for 'open'
	 */
	primus.on('open', function () {
		//console.info('primus:open', primus, 'isReco=', isReconnect, '| readyState:', primus.readyState, Date.now())
		if (primus !== this) {
			//console.warn('primus:open: taking new primus object', this, 'instead of', primus)
			primus = this;
		}
		voluntarilyClosed = false;

		exports.emit('open', isReconnect);

		// next time "open" is emitted, we know it's a reconnect
		isReconnect = true;
	});

	primus.on('offline', function () {
		if (!online) { return; }
		//console.info('primus:offline');
		online = false;

		if (wantConnection) {
			exports.emit('offline');
		}
	});

	primus.on('online', function () {
		if (online) { return; }

		//console.info('primus:online')
		if (primus !== this) {
			//console.warn('primus:online: taking new primus object', this, 'instead of', primus)
			primus = this;
		}

		online = true;

		// we try to reconnect only if we want the connection
		if (!wantConnection) { return; }
		exports.emit('online');

		// we don't try if an automatic reconnection is going to happen anyway
		if (primus.readyState !== Primus.CLOSED || primus.recovery.reconnecting()) { return; }

		//console.info('online: scheduling a reconnect in 500ms; readyState:', primus.readyState, Date.now())
		window.setTimeout(function () {
			if (primus.readyState === Primus.CLOSED && !primus.recovery.reconnecting()) {
				//console.info('primus:online calling primus.open() - readyState:',
				//	primus.readyState, 'reconnecting:', primus.recovery.reconnecting())
				primus.open();
			}
		}, 500);
	});

	/**
	 * Called when connection is ended. Primus may try to reconnect (see doc).
	 */
	primus.on('end', function () {
		//console.info('primus:end voluntary:', voluntarilyClosed, 'online:', online, 'wantCo:', wantConnection, this)
		// if offline Primus will retry when 'online' event comes
		if (!online) { return; }

		primus = null;

		// if voluntarily closed we are done

		if (!voluntarilyClosed) {
			// otherwise, we just lost our connection for good (we retried or cannot even retry)

			wantConnection = false;

			exports.disconnect('SOCKET_LOST');
		}
	});

	primus.on('reconnect scheduled', function (opts) {
		//console.info('primus:reconnect scheduled', opts, this)
		exports.emit('reconnecting', opts.attempt, url);
	});

	primus.on('data', function (data) {
		exports.emit(data._messageType, data);
	});

	/**
	 * Happens in rare case. Primus (per doc) does not throw even if we don't listen.
	 *  Saw it when proxy is down and we try to connect.
	 */
	primus.on('error', function (err) {
		//console.error('primus:error', err);
		exports.emit('error', err);
	});

	primus.open();
};


/**
 * Closes our connection (event 'lost' will not be emitted)
 */
exports.close = function () {
	voluntarilyClosed = true;
	wantConnection = false;

	if (primus) {
		primus.end(); // this also emits 'end' on primus
		primus = null;
	}
};


/**
 * @method module:connectionManager.disconnect
 *  @param {string} [reason] - if no reason given this is a voluntary close
 */
exports.disconnect = function (reason) {
	reason = reason || 'CLIENT_CLOSING';

	console.info('connectionManager.disconnect: reason=' + reason);

	// send "disconnecting" to the server and close primus
	// these are no-ops if primus is already gone, although close() does set some variables to make it clear
	// that this was voluntary and we're not looking to reconnect

	if (reason !== 'SOCKET_LOST') {
		exports.send('disconnecting', reason);
	}

	exports.close();

	exports.emit('disconnect', reason);
};


/**
 * Generic call from client to proxy.
 * @param {string} callName
 * @param {Object} data
 */
exports.send = function (callName, data) {
	primus.write({ call: callName, data: data });
};
```

**Comment by lpinca** [comment] 2015-10-02 15:06
I think that the issue is caused by the fact that the `end` method does not remove the [listeners](https://github.com/primus/primus/blob/66b5272041be41562ea1af46e340b3cb98c1fcb4/primus.js#L624-L630) of the `online` and `offline` events.
As result the listeners of those events will also be called on the old instance and in your case when this happens `primus` is already referencing the new instance.

As proof consider this example:
```js
(function () {
  var primus = new Primus({ strategy: false });

  primus.on('open', function () {
    console.log('open');
  }).on('end', function () {
    console.log('end');
  }).on('online', function () {
    console.log('online');
  }).on('offline', function () {
    console.log('offline');
  });

  setTimeout(function () {
    primus.end();
  }, 5000);
})();
```
If you wait for the `end` event and then switch the browser in offline and then online mode, you'll see that the `offline` and `online` listeners are still called.

If we use the `destroy` method instead of the `end` method and repeat the process an error is thrown.

**Comment by lpinca** [comment] 2015-10-03 10:51
@wizcorp-olivier try to remove the listeners of the `online` and `offline` events when you call the `end` method and see if this changes something.

**Comment by wizcorp-olivier** [comment] 2015-10-05 07:41
I tried calling destroy instead of end, and this solved the issue except for 2 error messages.
Even when calling destroy, the Primus instance # 1 is still receiving the online and offline event; I made a PR to remove these event handler upon destroy. The remaining question is over there too: do we want "offline" to always call "end"? (even if we are trying to reconnect)

**Comment by 3rd-Eden** [comment] 2015-10-05 13:01
Closing this as the offline/online issues are resolved. We should probably open a new issue about the `end` and `online` race condition.

**Closed by 3rd-Eden** 2015-10-05 13:01 UTC
Labels: investigate
