### ISSUE TITLE
Middleware example is outdated, can't get it working anymore

### ISSUE THREAD

**Issue by prashcr** [primus/primus#533] opened 2017-01-19 08:11 UTC
**Version:**
6.0.8

**Environment:**
  - **Operating system:** Windows 10
  - **Browser:** Google Chrome
  - **Node.js:** 7.3.0
  - **Transformer:** uws

**Expected result:**
Establish a connection between server and client
Able to set and read session object shared between Express and Primus

**Actual result:**
If I set  
```
primusSession.upgrade = true // or not set it at all
```
I can read and set the session object at `spark.request.session` as expected. However, I get the following error in my browser when trying to connect
```
WebSocket connection to 'ws://localhost:3000/gameserver?_primuscb=LcrjIwC' failed: Connection closed before receiving a handshake response
opening @ primus.js:3212
emit @ primus.js:300
reconnect @ primus.js:3246
emit @ primus.js:279
reconnect @ primus.js:2341
emitter @ primus.js:146
emit @ primus.js:1007
delay @ primus.js:849
tickedtock @ primus.js:1316
```  
  
If I set
```
primusSession.upgrade = false
```
The browser connects to the client successfullly however the middleware doesn't get called at all, and I can't set or read sessions in Primus.

**Steps to reproduce:**  
  
I'll try to set up a clean project to reproduce the issue, but here are code snippets for now.  
  
**primus-session.js**
```
/**
 * Slightly modified version of this middleware example
 * Notably, all references to cookie-parser have been rewritten since the latest express-session module doesn't use it anymore
 * https://github.com/primus/primus/blob/master/examples/middleware/session.js
 */

'use strict'

//
// Expose the configuration function.
//
module.exports = function configure(options) {
    const store = options.store
    const primus = this

    if (!store) {
        //
        // Throw an error when the session store is not passed.
        //
        const message = 'Session middleware configuration failed due to missing '
            + '`store` option'
        throw new Error(message)
    }

    //
    // The actual session middleware. This middleware is async so we need 3
    // arguments.
    //
    function session(req, res, next) {
        //
        // The session id is stored in the cookie
        //
        const sid = req.headers.cookie
        console.log('sid:', sid)

        //
        // Default to an empty session.
        //
        req.session = {}

        //
        // If we don't have a session id we are done.
        //
        if (!sid) return next()

        //
        // Grab the session from the store.
        //
        store.get(sid, function (err, session) {
            //
            // We don't want to kill the connection when we get an error from the
            // session store so we just log the error.
            //
            if (err) {
                primus.emit('log', 'error', err)
                return next()
            }

            if (session) req.session = session

            next()
        })
    }

    // Don't call this middleware in an Upgrade request
    session.upgrade = false
    session.http = true

    return session
}
```

**Express configuration**
```
// Sessions are shared between Express and Primus
const store = new expressSession.MemoryStore()
const session = expressSession({
    secret: 'change in production',
    resave: true,
    saveUninitialized: true,
    store,
})

// Express settings and middleware
app.set('port', process.env.PORT || 3000)
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'ejs')
app.use(logger('dev'))
app.use(express.static(path.join(__dirname, 'public')))
app.use(session)
```  
  
**Primus configuration**
```
const primus = new Primus(server, {
    pathname: '/gameserver',
    transformer: 'uws',
})

// Primus middleware
primus.use('session', primusSession, { store })
primus.use((req, res) => {
    console.log(req.session)
})
```

**Comment by lpinca** [comment] 2017-01-19 08:57
Hi,
I've just tried and the example works for me on macOS. This is the only change I did to make sure I was using the correct transformer:

```diff
diff --git a/examples/middleware/index.js b/examples/middleware/index.js
index 5037429..9a24261 100644
--- a/examples/middleware/index.js
+++ b/examples/middleware/index.js
@@ -52,7 +52,7 @@ app.get('/', function index(req, res) {
 // Create an HTTP server and our Primus server.
 //
 var server = http.createServer(app)
-  , primus = new Primus(server);
+  , primus = new Primus(server, { transformer: 'uws' });
 
 //
 // Here we add the `cookie-parser` middleware and our session middleware. The
```

**Comment by lpinca** [comment] 2017-01-19 09:10
> If I set
> ```
> primusSession.upgrade = false
> ```
> The browser connects to the client successfullly however the middleware doesn't get called at all, and I can't set or read sessions in Primus.

This is expected when using a WebSocket only transformer like uws as only upgrade requests are made from client to server.

Anyway the session middleware should run for both upgrade and non-upgrade requests to make sure that it works with all transformers.

**Comment by prashcr** [comment] 2017-01-19 11:11
Thanks for the clarification.

To confirm, you're saying that the example code works for you? I haven't tried the example actually since it gives me an unrelated error (some path issue with require()).  
  
I was hoping you could try modifying the example with a recent version of express-session that doesn't use cookie-parser for which I adjusted the middleware accordingly and pasted above. If not, no worries.

**Comment by prashcr** [comment] 2017-01-19 11:16
My bad, I forgot to run `npm install` in the top level directory while trying to run the example. I can confirm that the example works.

**Comment by lpinca** [comment] 2017-01-19 11:16
Yeah, it works for me but I didn't test on Windows. I've installed the latest versions of the dependencies including the latest `express-session`.

According to the [docs](https://github.com/expressjs/session#sessionoptions) you can still use `cookie-parser` which is kinda useful in order to avoid parsing the cookies yourself in the primus middleware.

**Comment by lpinca** [comment] 2017-01-19 11:24
You can also try to use `express-session` directly as a Primus middleware. The reason for which the example uses a custom one is that it didn't work properly, see https://gist.github.com/lpinca/11222004.

I don't know if the issue persists.

**Comment by prashcr** [comment] 2017-01-19 11:35
I tried using express-session directly in `primus.use()`, but I'm just getting `Connection closed before receiving handshake response`.

**Comment by prashcr** [comment] 2017-01-19 11:56
I made a minimal project that reproduces my issue, let me know how it works for you.

https://github.com/prashcr/primus-session-test

**Comment by lpinca** [comment] 2017-01-19 12:32
@prashcr works for me on macOS.

**Comment by prashcr** [comment] 2017-01-19 14:06
I tried this on my macbook and it does work, welp.

Any idea where I could dig deeper?

**Comment by lpinca** [comment] 2017-01-19 14:09
I'm honestly not sure do other WebSocket transformers behave the same? For example `websockets` or `faye`?

**Comment by prashcr** [comment] 2017-01-19 14:25
Hmm, it seems to be unique to `uws`.  
  
It connects as expected with `websockets` and `faye`.  
  
`sockjs` gives an error about `req.session.touch()` not being implemented

**Comment by lpinca** [comment] 2017-01-19 14:29
Can you try with primus@6.0.7 and uws?

**Comment by prashcr** [comment] 2017-01-19 14:38
`sockjs` connects now, however printing out `req.session` seems to just show an id rather than a Session instance as is the case with `websockets` or `faye`

**websockets or faye**
```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
```

**sockjs**
```
1ducmhia // some random id of this length
```

`uws` still broken unfortunately.

**Comment by lpinca** [comment] 2017-01-19 16:07
@prashcr sockjs is "special" as it overrides the `session` property. If you change the Primus example like this:

```diff
diff --git a/examples/middleware/index.js b/examples/middleware/index.js
index 5037429..45a1ada 100644
--- a/examples/middleware/index.js
+++ b/examples/middleware/index.js
@@ -52,7 +52,7 @@ app.get('/', function index(req, res) {
 // Create an HTTP server and our Primus server.
 //
 var server = http.createServer(app)
-  , primus = new Primus(server);
+  , primus = new Primus(server, { transformer: 'sockjs' });
 
 //
 // Here we add the `cookie-parser` middleware and our session middleware. The
@@ -66,7 +66,7 @@ primus.on('connection', function connection(spark) {
   //
   // Our session data can now be read from `spark.request.session`.
   //
-  spark.write(JSON.stringify(spark.request.session, null, '  '));
+  spark.write(JSON.stringify(spark.request.banana, null, '  '));
 });
 
 //
diff --git a/examples/middleware/session.js b/examples/middleware/session.js
index e12b46e..47bb6ae 100644
--- a/examples/middleware/session.js
+++ b/examples/middleware/session.js
@@ -33,7 +33,7 @@ module.exports = function configure(options) {
     //
     // Default to an empty session.
     //
-    req.session = {};
+    req.banana = {};
 
     //
     // If we don't have a session id we are done.
@@ -53,7 +53,7 @@ module.exports = function configure(options) {
         return next();
       }
 
-      if (session) req.session = session;
+      if (session) req.banana = session;
 
       next();
     });
```

it works and that's another reason why `expression-session` shouldn't be used directly.

---

> My bad, I forgot to run npm install in the top level directory while trying to run the example. I can confirm that the example works.

So the Primus example works for you on Windows when using uws?

**Comment by lpinca** [comment] 2017-01-19 21:50
@prashcr I've managed to reproduce the issue on Windows without Primus.

```js
'use strict';

const WebSocket = require('uws');
const http = require('http');

const wss = new WebSocket.Server({ noServer: true });
const server = http.createServer();

server.on('upgrade', (request, socket, head) => {
  setTimeout(() => {
    wss.handleUpgrade(request, socket, head, () => console.log('connection'));
  }, 100);
});

server.listen(3000, () => console.log('listening on *:3000'));
```

The connection cannot be established when creating a WebSocket from a browser (tested on Firefox). For example using

```js
const ws = new WebSocket('ws://localhost:3000');
```

from a browser console.

The same example works when using ws instead of uws.

**Comment by prashcr** [comment] 2017-01-19 22:22
>> My bad, I forgot to run npm install in the top level directory while trying to run the example. I can confirm that the example works.  
>
> So the Primus example works for you on Windows when using uws?

I meant that the middleware example in `/examples` runs without any modification (using `websockets` as default transformer).  
  
---

Hmm, that's surprising. Feel free to close the issue, I'll create another one at `uws`. Thanks for all the help!

**Comment by lpinca** [comment] 2017-01-19 22:25
Closing then, comment or reopen if needed.

**Closed by lpinca** 2017-01-19 22:25 UTC

**Comment by lpinca** [comment] 2017-01-20 07:18
@prashcr in the uws issue you should point out that the `socket.destroy()` is called on the same tick of `uws.native.transfer()` so the last example posted by Alex is not what happens.
