### ISSUE TITLE
PaaS Hosting and Primus

### ISSUE THREAD

**Issue by akreienbring** [primus/primus#345] opened 2015-02-20 14:41 UTC
Just wanted to share my (sad) experiences when searching a PaaS Provider for my server application using primus and primus-rooms. (with websockets transformer)

Heroku:
It is partly working if you use only one 'dyno'. That means no load balancing. Even then the application goes idle every 55 seconds and kills all spark connections. Support tries to help but can't figure out what's happenig. With two dynos even connection errors occur. Most likely becaus load balancing does not support 'sticky sessions'

AWS Beanstalk:
Working, but only without nginx proxy and without load balancing. All hints and tricks I found so far to configure nginx by using 'ebextension' are NOT working.

Anyone made better experiences or has any useful hints regarding the two providers mentioned?

**Comment by 3rd-Eden** [comment] 2015-02-20 15:19
Heroku is a known problem because they don't have sticky load balancing so I personally never recommend it. I haven't heard about the 55 seconds bug before so it's quite odd that something like this is happening. It's probably not even worth the investigation until Heroku fixes their load balancers.

I would have adviced you to look at Nodejisu for your real-time hosting as they do have proven track record in hosting real-time applications, our demo is also hosted on them (side note, I work at Nodejitsu). But we've recently been aquired so the sign-ups are closed. What you could do instead is look at modulus.io they are also a Node.js based paas and have a sticky load balancer (written in Go). 

For all my own major projects that use real-time I just use Linux boxes with Docker instances running on them and a HAProxy load balancers which orchestrates all the things. Hosting a real-time application your self is usually the best solution as you have much more fine grain control over the way sockets are handled by the operating system as regular servers are turned for short lived connections, you might want to do some addition turning to ensure that long lived connections work as optimal as possible.

**Comment by akreienbring** [comment] 2015-02-24 09:09
Yeah, all together it's kind of weird. Maybe it's simply caused by the fact that it seems to be fairly complicated to find working solutions:

The Heroku support simply doesn't know why the 55 sec. timeouts do occur. Or maybe they don't know what to listen for to be aware of the pings that the primus clients sends out. As you say: Sticky Session are not even an option for them.

Beanstalk on the other hand seems to actively block the extensive usage of websockets, as they simply do not allow to do the configuration on nginx that are neccessary to use it with websockets. And documentation on this is not existent. 

And Nodejitsu... yes I've read the blog entry... I don't understand why they closed the sign-ups. Given that Go Daddy hopes to make money with existing and future Nodejitsu customers?

Maybe I'll have another look at Modulus. Don't remember exactly why I wiped them from my list. Maybe it was because they don't offer a free startup plan....

**Comment by Maraumax** [comment] 2015-02-24 13:20
I use Primus with AWS Beanstalk carefree. I set "Proxy server" to none and i set up tcp and ssl to elb (instead of http / https).

**Comment by akreienbring** [comment] 2015-02-24 14:10
@Maraumax: Yes, as I wrote in my first post it is indeed working with no proxy server in front of my application. 
How exeactly did did you add https support to your server? Maybe that's an alternative to nginx....

**Comment by Maraumax** [comment] 2015-02-24 14:15
Just by adding the certificate on the load balancer and then redistributing traffic to instances over tcp.

`
ELB SSL 443 -> TCP 80 to EC2
`

**Comment by akreienbring** [comment] 2015-02-24 14:17
For all those who are interested... you may have a look here:
https://gist.github.com/adamgins/f99635447a1239289460
This guy had a long session with AWS support in december and finally had some success in using nginx and sticky sessions with ELB

**Comment by akreienbring** [comment] 2015-02-24 14:19
@Maraumax: Do you need a custom domain name for that to work? And are you allowed to use a self signed certificate?

**Comment by Maraumax** [comment] 2015-02-24 14:22
@akreienbring I use aws S3 for dns (with alias to ELB) and a signed certificate

**Comment by akreienbring** [comment] 2015-02-24 14:31
More information on using and configuring ELB here:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.elb.html

**Comment by akreienbring** [comment] 2015-03-01 08:47
Just for the records: I went over to Modulus, created an account, threw in my server and it was running without any restrictions or connection issues immediatly. The whole process took me about 20 minutes.

**Comment by akreienbring** [comment] 2015-03-04 20:47
Hello, just some news about Heroku. The support is encouraged to fix the 55 sec. issue. They even implemented a HAProxy with support for sticky session on an experimental routing layer...

After some more testing an important question came up:

Is primus really sending pings when using the websocket 'ws' transformer?
As described here: https://github.com/websockets/ws/blob/master/doc/ws.md#websocketpingdata-options-dontfailwhenclosed

Or do I have to implement the pings in my client application?

Any information on this is greatly appreciated as we have a great chance here to get rid of any connection issues regarding heroku...

**Comment by 3rd-Eden** [comment] 2015-03-04 21:30
@akreienbring We're sending `primus::ping::<value>` messages over the established connection. This way we can send bidirectional pings (websocket.ping() on the client does not exist unfortunately)

**Comment by 3rd-Eden** [comment] 2015-03-04 21:31
See https://github.com/primus/primus#heartbeats-and-latency for additional information about the heart beats

**Comment by akreienbring** [comment] 2015-03-07 14:29
How can I test for that ping?

something like:
```
			primus.on('outgoing::url', function connectionURL(url) {
				console.log(url.???);
			});
```
?

**Comment by akreienbring** [comment] 2015-03-28 12:15
Hello,
I just installed version 3.0.2 of primus and still can't see any pings. Neither on the client on
```
			primus.on('outgoing::ping', function connectionData(packet) {
				$log.debug("primus just pings: " + JSON.stringify(packet));
			});
```
nor on the server on
```
		spark.on('heartbeat', function (message) {
			console.log("heartbeat message is " + JSON.stringify(message));
		});
```
Im using 'websockets' transformer.
It still looks as if no ping is ever send from client to server.

**Comment by akreienbring** [comment] 2015-03-28 13:12
I think I found the bug...

Your readme states a default ping interval of 25000 ms. BUT your source code (of generated primus client defines:
```
  // Heartbeat ping interval.
  options.ping = 'ping' in options ? options.ping : 35990000;
```
which is nearly 600 min.(!)

As soon as I set the options.ping to 25000 by myself I can check the outgoing pings with
```
			primus.on('outgoing::ping', function connectionData(packet) {
				$log.debug("primus just pings: " + JSON.stringify(packet));
			});
```
However. the heartbeat event on the server is still not triggered...

**Comment by lpinca** [comment] 2015-03-28 15:51
@akreienbring any way to reproduce that?
In my compiled client the value is correct:
```
// Heartbeat ping interval.
options.ping = 'ping' in options ? options.ping : 25000;
```

**Comment by lpinca** [comment] 2015-03-28 15:54
@akreienbring `primus@3.0.2` does not have the `heartbeat` event feature. You should install the master branch to get that.

**Comment by akreienbring** [comment] 2015-03-29 10:55
@lpinca 
I just checked again. I even deleted the generated primus.js. Still the same.
```
  // Connection timeout duration.
  options.timeout = 'timeout' in options ? options.timeout : 10e3;

  // Stores the back off configuration.
  options.reconnect = 'reconnect' in options ? options.reconnect : {};

  // Heartbeat ping interval.
  options.ping = 'ping' in options ? options.ping : 35990000;

  // Heartbeat pong response timeout.
  options.pong = 'pong' in options ? options.pong : 10e3;
```
This is how I generate the file:
```
	primus.save(__dirname +'/../public/js/primus.js');
```

**Comment by lpinca** [comment] 2015-03-29 11:42
```js
// test.js
var EventEmitter = require('events').EventEmitter
  , Primus = require('primus')
  , primus;

primus = new Primus(new EventEmitter());
primus.save(__dirname + '/primus.js');
```
```sh
macbook:test luigi$ node test.js 
macbook:test luigi$ cat primus.js | grep "'ping' in options"
  options.ping = 'ping' in options ? options.ping : 25000;
macbook:test luigi$
```
Mind to share your configuration (plugins, transformer, parser etc.)?

**Comment by akreienbring** [comment] 2015-03-29 12:06
Playing around with your example I can reproduce that
```
primus = new Primus(new EventEmitter(), {timeout: 36000000 });
```
leads to
```
  // Heartbeat ping interval.
  options.ping = 'ping' in options ? options.ping : 35990000;
````

**Comment by lpinca** [comment] 2015-03-29 12:32
@akreienbring that is expected, if you change the `timeout` value we update the ping interval accordingly as there is no point on keep pinging every 25 s, it will be only useless overhead.
See https://github.com/primus/primus/blob/a8e06bfa93565338ff7b0cd03ab307857e986160/index.js#L546.

**Comment by akreienbring** [comment] 2015-03-30 08:02
That makes sense!
I configured that setting because I saw permanent disconnections when I used the engine.io transformer under an earlier version of primus.
Would be interesting to check if that still occures with the current versions...

Thanks for looking into this and clarifying things.

**Comment by akreienbring** [comment] 2015-04-12 07:54
FYI:
Heroko documented their 'sticky session' feature here:
https://devcenter.heroku.com/articles/session-affinity

**Comment by trustmaster** [comment] 2015-04-17 09:23
@akreienbring did Heroku Session Affinity fix the idle connection timeout for you? We have enabled it but it doesn't seem to fix the issue.

**Comment by akreienbring** [comment] 2015-04-18 06:17
@trustmaster no. You need to send frequent pings to stay connected. See above.

**Comment by akreienbring** [comment] 2015-04-19 19:34
These are my current findings:

As long as I send frequent pings (every 25000ms) Heroku does not kick me out. 
As long as I only use one 'dyno' everything is fine.
As soon as I add another 'dyno' I can see in the heroku logs that my socket data arrives on the server, but I never get any response :-(

My App works like this: Client App sends something, Server does something and sends data to one ore more clients. 

According to the primus documentation:
```
Scaling Primus is as simple as sticking it behind a load balancer that supports sticky sessions
and run multiple versions of your application. This is a vital feature that your load balancer needs
to support. This ensures that the incoming requests always go back to the same server. If your
load balancer does not support sticky sessions, get another one...
```
Is this true? Is there anything else I have to do? Despite adding dynos on Heroku? Redis? Session management? Anything?

Any help is appreciated and I think scaling primus on popular hosting platforms is interesting for a lot of people.

**Comment by lpinca** [comment] 2015-04-19 20:06
@akreienbring the documentation is correct, but a server (dyno) knows only its clients by default.

You are probably looking for a way to communicate between multiple primus instances. Take a look at https://github.com/primus/omega-supreme and https://github.com/primus/metroplex or pub/sub system.

**Comment by hunterloftis** [comment] 2015-04-20 23:23
Ping me (hunter@heroku.com) if you'd like to join the session affinity beta.

**Comment by 3rd-Eden** [comment] 2015-08-25 06:10
I'm going to close this issue as all issues are fixed and heroku now supports session affinity for all users. 

https://blog.heroku.com/archives/2015/4/28/introducing_session_affinity

**Closed by 3rd-Eden** 2015-08-25 06:10 UTC
Labels: discussion
