### ISSUE TITLE
Can't successfully load client with WebPack+babel

### ISSUE THREAD

**Issue by ahri** [primus/primus#444] opened 2016-03-07 09:37 UTC
**Version:** 5.0.0

**Environment:**
  - **Operating system:** Windows 10, 64bit
  - **Browser:** Chrome 48.0.2564.116 m
  - **Node.js:** 5.4.0

**Expected result:** client imported successfully in browser

**Actual result:** webpack mutates "this" to "undefined" on line 8 of client (`})("Primus", this, function wrapper() {`), resulting in: Uncaught TypeError: Cannot set property 'Primus' of undefined

**Steps to reproduce:**
1. generate 'websocket' client
2. require the client: `const Primus = require('../api/primus');`
3. use webpack (with babel) to generate bundle
4. open page referencing bundle

**Comment by ahri** [comment] 2016-03-07 10:38
As a workaround I've deployed the primus.js as a static script, referenced from the browser alongside my bundle.js, and declared 'Primus' a global in my eslint config.

It would be neater to be able to simply require it though!

**Comment by lpinca** [comment] 2016-03-07 11:33
This is probably a duplicate of https://github.com/primus/primus/issues/383.
If you can find a way to fix this it would be very much appreciated.

**Comment by MystK** [comment] 2016-03-08 03:25
Here is how I'm doing it in webpack

`import "!script!./static/primusClient.js"`

**Closed** 2016-04-25 17:34 UTC

**Comment by kkemple** [comment] 2017-03-06 14:44
In case anyone else runs into this:
https://github.com/kkemple/primus-webpack-plugin

**Comment by koraysels** [comment] 2018-11-14 11:51
I really am having prblems with this. als o that webpack plugin does not work with webpack 4 and babel 7

**Comment by koraysels** [comment] 2018-11-14 14:54
I fixed by having Primus write the client lib to a file and then importing it in my client code. I had to exclude it from the babel-loader in webpack though..
