### ISSUE TITLE
is primus connected method for browser??

### ISSUE THREAD

**Issue by siddo420** [primus/primus#388] opened 2015-08-06 23:50 UTC
I apologize in advance if this is a duplicate issue (googled already) or already mentioned in docs (searched there as well).

Is there an easy/efficient way to find out if the primus connection is up and running or not by calling a method? I think, I am looking for a simple primus.isConnected() or primus.is_connected() etc method.

I was thinking of using open, reconnected, end, close etc event handlers to keep track of connection but I thought I should ask before I do that.

**Comment by lpinca** [comment] 2015-08-07 05:46
Hi, you can listen to the `readyStateChange` event or you can check the `readyState` property directly.
```js
if (primus.readyState === Primus.OPEN) {
  // Do stuff.
}
```

**Comment by siddo420** [comment] 2015-08-07 05:56
Thanks.

Another small question (or perhaps correction/confirmation):
 
After calling primus.end() (https://github.com/primus/primus#primusend), can primus.open() be called to open the connection again?

**Comment by lpinca** [comment] 2015-08-07 06:06
Yes, that works.

From the documentation:
> If you want to manually control the reconnection you can call primus.end() to close the connection and primus.open() to enstablish a new one. Be sure to use primus.open() correctly, see below for details.

...

> **primus.open()**
>
> This method opens a connection with the server. By default it is called automatically when the Primus instance is created, but there are cases where it's desiderable to open the connection manually. To do this set the manual option to true and when you have the Primus instance call the method:
>
> ```js
> primus.open();
> ```
>
> When you call primus.open() you should make sure that the connection is totally dead (e.g. after an end event) and primus isn't already trying or planning to reconnect.

**Comment by siddo420** [comment] 2015-08-07 13:04
I've read that but I got confused by the details for primus.end() (does not mention primus.open() specifically). It looks like a documentation bug.

```
primus.end()

When you want to close the connection you can call the primus.end() method. 
After this the connection should be considered dead and a new connection needs 
to be made using Primus.connect(url) or primus = new Primus(url) 
if you want to talk with the server again.
```

**Comment by lpinca** [comment] 2015-08-07 13:27
Not a bug, that also works, but replaces the current primus instance with a new one.
Maybe it can be improved, PR is welcome.

**Comment by lpinca** [comment] 2015-08-10 06:08
Closing this, but please post back if you need more help.

**Closed by lpinca** 2015-08-10 06:08 UTC
