### ISSUE TITLE
No createSocket method in client library

### ISSUE THREAD

**Issue by tejohnso** [primus/primus#571] opened 2017-04-06 17:32 UTC
The docs state:

### Client library

As most libraries come with their own client-side framework for making the connection we've also created a small wrapper for this. The library can be retrieved using....
`primus.save(__dirname +'/primus.js');`

Then:

>The client-side library has been made compatible with Node.js so the same code base can be re-used for server side connections. 

Then: 

>2. You might need to connect from a different node process where you don't have access to your primus instance and the compatible Socket instance. For these cases there a special **createSocket** method...

**BUT** there is no *createSocket* method on the client library.

**Comment by lpinca** [comment] 2017-04-06 17:40
Yeah, maybe it's not clear but what the docs try to say is that you can use `Primus.createSocket()` from another Node.js process without explicitly creating a new Primus instance and an HTTP server.

Makes sense?

**Comment by tejohnso** [comment] 2017-04-06 17:52
But that's not `Primus` from the client library, then?  I think the confusion is that in **1.** `new Primus` is the `Primus` from the client library and in **2.** `Primus.createSocket` is the `Primus` from the server library.  Is that right?

**Comment by tejohnso** [comment] 2017-04-06 17:57
Actually **1.** is an example of connecting within the same process as the server so it's also the server-side library.  I'm not sure why the client-side library is mentioned at all.

**Comment by lpinca** [comment] 2017-04-06 18:02
Yes, both are example of https://github.com/primus/primus#connecting-from-the-server (they are in the same section).
There is a separate section for the browser: https://github.com/primus/primus#connecting-from-the-browser

**Comment by lpinca** [comment] 2017-04-06 18:17
> The client-side library has been made compatible with Node.js so the same code base can be re-used for server side connections.

Is this the cause of the confusion? This sentence wants to say that the same code is used for both browsers clients and server clients.

**Comment by tejohnso** [comment] 2017-04-06 18:45
That is the cause of the confusion.  I don't see how the same code can be used for both browser and server clients.  On the browser you can't use `Primus.createSocket` and on the server you can.

**Comment by lpinca** [comment] 2017-04-06 18:51
Ok, the problem is that it is not referring to the code in the examples but the actual client code: https://github.com/primus/primus/blob/a0d5e5fe425b4a3bf342e14b813f487163fed9e6/primus.js

Feel free to send a PR to improve the wording, most of the docs has been written by non native speakers.

**Comment by lpinca** [comment] 2017-04-06 20:11
Closing this, please comment or reopen if needed.

**Closed by lpinca** 2017-04-06 20:11 UTC
