### ISSUE TITLE
How to get the underlying ws object from a spark?

### ISSUE THREAD

**Issue by computersarecool** [primus/primus#492] opened 2016-09-12 08:47 UTC
**Version:**
Latest
**Environment:**
- **Operating system:**
  All
  - **Browser:**
    Chrome
- **Node.js:**
  v4.2.1

I am trying to use this library with [osc.js](https://github.com/colinbdclark/osc.js/).  That library has a constructor that expects to connect to a WebSocket [Instance (from the `ws` library).](https://github.com/colinbdclark/osc.js/#web-sockets-in-nodejs)

Is it possible to expose the underlying `ws` object when I am using websockets as the transformer?  I would basically like to treat the `spark` that is returned as the underlying WebSocket, but passing it into osc.js doesn't "just work" and I am not sure how to extract the actual `ws`.

**Comment by lpinca** [comment] 2016-09-12 09:04
It is not possible as `ws` is private, see https://github.com/primus/primus/blob/0458cfdeaae0e80df310bb97d0a63e8fddd52c3f/transformers/websockets/server.js#L34-L63.

**Comment by computersarecool** [comment] 2016-09-12 09:09
I see. Was it kept private for a reason?

**Comment by lpinca** [comment] 2016-09-12 09:23
I think the reason was to prevent people from messing up with it and avoid memory leaks.
Also if we expose it in the `spark` object we should do it for all transformers not only `websockets` and I don't know if this can be done reliably for all of them.

cc: @3rd-Eden

**Comment by seiyria** [comment] 2017-05-18 00:09
I'm getting an error with `reserved fields must be empty (1002)` and having access to the underlying object would make it so I can swallow that error. Right now, it does not seem that `spark.on('error')` catches it for some reason. Worse yet, I have no idea how to reproduce this error, it just happens.

**Comment by lpinca** [comment] 2017-05-18 05:55
@seiyria the error is [forwarded](https://github.com/primus/primus/blob/4073860dc1c515943fbb276c51936757a50b1a3a/transformers/websockets/server.js#L53) to the spark.

Anyway this particular error means that the client is sending a malformed WebSocket frame. Hard to say if it is done intentionally or not.

**Comment by lpinca** [comment] 2018-11-17 16:30
Fixed by #703.

**Closed by lpinca** 2018-11-17 16:30 UTC
