### ISSUE TITLE
primus doesn't accept custom path with engine.io

### ISSUE THREAD

**Issue by balakrishna222111** [primus/primus#774] opened 2021-07-08 06:35 UTC
**5.1.2**

**Environment:**
  - **Linux:**
  - **chrome:**
  - **express.js:**

**Expected result:**
"https://app.application.com/mycustompath/?_primuscb=*******************"

**Actual result:**
"https://app.application.com/?_primuscb=*******************"

**Steps to reproduce:**

`var server = http.createServer(app);
var Primus = require('primus');
const Session = require('server/session');
var primus = new Primus(server, {
  transformer: 'engine.io',
  pathname:"/mycustompath/primus",
  compression: true,
  transport: {
    cookie: Session.getEngineIOCookieName()
  }
});

var Connection = require('server/connection');
primus.on('connection', function (spark) {
  Connection.create(spark);
});

primus.on('disconnection', function (spark) {
  Connection.destroy(spark);
});

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);`

**Comment by balakrishna222111** [comment] 2021-07-12 02:20
@lpinca  Could you please check this bug

**Comment by lpinca** [comment] 2021-07-13 09:16
I cannot reproduce the issue:

```js
'use strict';

const Primus = require('primus');
const http = require('http');
const fs = require('fs');

const server = http.createServer(function (req, res) {
  if (req.url === '/client.js') {
    res.setHeader('Content-Type', 'application/javascript');
    fs.createReadStream(__dirname + '/client.js').pipe(res);
    return;
  }
  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(__dirname + '/index.html').pipe(res);
});

const primus = new Primus(server, {
  pathname: '/mycustompath/primus',
  transformer: 'engine.io'
});

primus.on('connection', function (spark) {
  console.log(spark.id, 'connected');
});

server.listen(3000, function () {
  console.log('listening on port 3000');
});
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="/mycustompath/primus/primus.js"></script>
    <script>
      (function () {
        var primus = new Primus({ strategy: false });

        primus.on('open', function open() {
          console.log('open');
        });
      })();
    </script>
  </body>
</html>
```

![Immagine 2021-07-13 111533](https://user-images.githubusercontent.com/1443911/125425901-cf5b72a1-79cb-4449-85d8-ece31b3acaa0.png)

Did you rebuild the client?

**Comment by balakrishna222111** [comment] 2021-07-13 11:23
@lpinca  Here we are hard coding this `/mycustompath`  value   here  `<script src="/mycustompath/primus/primus.js"></script>`  can we make it dynamic

**Comment by lpinca** [comment] 2021-07-13 12:22
It does not matter, that's just where the `Primus` client is found.

```js
const Primus = require('primus');
const http = require('http');
const fs = require('fs');

const server = http.createServer(function (req, res) {
  if (req.url === '/primus-client.js') {
    res.setHeader('Content-Type', 'text/javascript');
    fs.createReadStream(__dirname + '/primus-client.js').pipe(res);
    return;
  }

  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(__dirname + '/index.html').pipe(res);
});

const primus = new Primus(server, {
  pathname: '/mycustompath/primus',
  transformer: 'engine.io'
});

primus.save(__dirname + '/primus-client.js');

primus.on('connection', function (spark) {
  console.log(spark.id, 'connected');
});

server.listen(3000, function () {
  console.log('listening on port 3000');
});
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="/primus-client.js"></script>
    <script>
      (function () {
        var primus = new Primus({ strategy: false });

        primus.on('open', function open() {
          console.log('open');
        });
      })();
    </script>
  </body>
</html>
```

**Comment by balakrishna222111** [comment] 2021-07-13 14:36
- After your changes am facing new issues
My "**index.html**" code attached below
`<script src="primus.js"></script>
`
- My "**run.js**" code attached below

` var Primus = require('primus');
const Session = require('server/session');
var primus = new Primus(server, {
  pathname:"/pepsi/primus",
  transformer: 'engine.io',
  compression: true,
  transport: {
    cookie: Session.getEngineIOCookieName()
  }
});

primus.save(__dirname + '/primus.js');

var Connection = require('server/connection');
primus.on('connection', function (spark) {
  Connection.create(spark);
});

primus.on('disconnection', function (spark) {
  Connection.destroy(spark);
});
`

![image](https://user-images.githubusercontent.com/22685723/125471234-be3e71ae-2c75-43f9-8cf4-14bf626bf7d0.png)

**Comment by lpinca** [comment] 2021-07-13 14:40
It means the `Primus` constructor is not found. Ensure that the client script it correctly loaded.

**Comment by balakrishna222111** [comment] 2021-07-13 14:42
I closed browser and opened again now these issue arises
![image](https://user-images.githubusercontent.com/22685723/125472190-d6ed6684-4e09-4d52-b3b9-137550cad959.png)

**Comment by balakrishna222111** [comment] 2021-07-13 14:44
previoulsy `primus.js` folder should be under javascript folder 
but now it was not there

**Comment by lpinca** [comment] 2021-07-13 14:45
I can't debug your code, sorry. That's up to you.

**Comment by lpinca** [comment] 2021-07-13 14:48
You probably just have to save the client lib under the javascript folder and get it from there.

```js
primus.save('/path/to/javascript' + '/primus.js');
```

```html
<script src="/path/to/javascript/primus.js"></script>
```

**Comment by balakrishna222111** [comment] 2021-07-13 17:31
![image](https://user-images.githubusercontent.com/22685723/125498277-5d323b65-6ce1-4ba4-8bf7-5374192113f8.png)
- Now it's Navigating to the engineio
- primus.js file was adding properly 
![image](https://user-images.githubusercontent.com/22685723/125498455-812063e9-a73b-44c1-9eeb-b32756bb1feb.png)
- **index.html**
![image](https://user-images.githubusercontent.com/22685723/125498514-6869b103-a6b4-4561-96ac-96a834ff993f.png)
- **run.js**
- 
![image](https://user-images.githubusercontent.com/22685723/125498649-ca850f21-2fdf-40a8-9193-ebd2fdf78a4c.png)

**Comment by lpinca** [comment] 2021-07-13 18:19
That is a CORS issue because you are sending a cross origin request. See https://github.com/primus/primus#getting-started and https://github.com/socketio/engine.io#methods-1.

**Comment by balakrishna222111** [comment] 2021-07-14 05:27
In express.js file already enabled that 
![image](https://user-images.githubusercontent.com/22685723/125567579-821126d4-c7fb-4610-84f4-2faae1776811.png)

**Comment by lpinca** [comment] 2021-07-14 06:36
Requests for primus/engine.io are not handled by express.

**Comment by balakrishna222111** [comment] 2021-07-14 07:52
do i need to update in client side

**Comment by lpinca** [comment] 2021-07-14 08:00
No, server side.

**Comment by balakrishna222111** [comment] 2021-07-14 08:09
![image](https://user-images.githubusercontent.com/22685723/125587004-2544450d-2b64-46d7-ac4e-47b5e0cd5998.png)
is this fine

**Comment by lpinca** [comment] 2021-07-14 08:18
No, `cors` is not a valid primus option. It should eventually be `origins` but it depends on your architecture. Is https://api.autoscheduler.ai/ running primus? From the screenshots it seems to run a plain engine.io server. If so you should use the `cors` option as per https://github.com/socketio/engine.io#methods-1 and things might not work as you expect if you use a primus client to connect to it.

P.S. I can't do your work.

**Comment by balakrishna222111** [comment] 2021-07-14 10:04
Please remove this `P.S. I can't do your work.`

**Comment by lpinca** [comment] 2021-07-14 10:26
I'm closing this. Let me know if it should stay open.

**Closed by lpinca** 2021-07-14 10:26 UTC
