### ISSUE TITLE
Dist 2.1.0 With Engine.IO 1.0.5 Connection

### ISSUE THREAD

**Issue by alexcurtis** [primus/primus#196] opened 2014-03-26 16:28 UTC
I recently upgraded to the latest Primus + Engine.io versions. It seems to infinitely loop when creating a connection from the browser. primus.on('connection') seems to be repeatedly triggered on a single connection.

**Comment by STRML** [comment] 2015-09-24 15:42
I've been seeing this crop up again intermittently with the polling transport. Will post again once I have a working test case.

**Comment by episodeyang** [comment] 2015-10-08 02:46
I am seeing this as well with the newest release. Not sure how to reproduce yet. 

One of the things is that I might have tons of clients with older version trying to reconnect. Would this be a factor?

**Comment by lpinca** [comment] 2015-10-08 05:50
@episodeyang It shouldn't as this is a server-side issue.

**Comment by episodeyang** [comment] 2015-10-08 14:27
I see, thanks! I will keep you posted if I see this happen again.

**Comment by episodeyang** [comment] 2015-10-08 14:37
okay this keeps happening

!(screen shot)[https://www.dropbox.com/s/iwsfqtxny1c9f2e/Screenshot%202015-10-08%2009.36.13.png?raw=0]

**Comment by STRML** [comment] 2015-10-08 14:50
So this is a Node v4 issue that has to do with how Buffers have changed - see https://github.com/nodejs/node/issues/3025

Essentially `Buffer.concat([String])` never should have worked, but `Buffer.concat(['foo'])` actually did and would return `'foo'`.

The actual change was:

> Buffer.concat() now always creates a new buffer, even if only called with one element.

This likely has to be fixed in engine.io itself.

**Comment by episodeyang** [comment] 2015-10-08 14:52
Thanks!

is there still an engine.io issue for this?

and also for the mean while, what other transport would you recommend if I need this in production?

best, Ge

**Comment by STRML** [comment] 2015-10-08 14:55
No issue, I've created one.

This is a DoS vector so we need to figure out a solution ASAP. In the meantime you could switch to SockJS.

**Comment by episodeyang** [comment] 2015-10-08 14:56
Thanks! will do.

**Comment by STRML** [comment] 2015-10-08 17:45
@episodeyang What version of Node are you using? I [was able to reproduce](https://github.com/socketio/engine.io/pull/305#issuecomment-146635264) but only on `0.10.x`.

**Comment by lpinca** [comment] 2015-10-08 19:33
I've just noticed that the original fix of this issue is no longer needed in node `0.12` and above.

**Comment by STRML** [comment] 2015-10-08 19:35
Primus is still supporting `0.10` though, right?

**Comment by lpinca** [comment] 2015-10-08 19:36
Yes, we offically dropped `0.8` support in version `4.0.0`.

**Comment by lpinca** [comment] 2015-10-08 19:50
If https://github.com/socketio/engine.io/pull/305 will get merged we can also remove the workaround proposed here as that patch also fixes the issue on node `0.10`.

**Comment by 3rd-Eden** [comment] 2015-10-09 06:19
@STRML Yes `0.10` is still support in `4.0.0` but will be dropped in `5.0.0` as I want to move to the whole codebase to node `4.0.0` as soon as possible so we can start writing our in ES6

**Comment by episodeyang** [comment] 2015-10-09 06:20
Sigh I started working on migrating to 0.12.7 four hours ago. I'm still working on it :/

How is the node 4.0.0 support for libraries so far?

**Comment by lpinca** [comment] 2015-10-09 06:29
@episodeyang If I was you migrating from `0.10`, I would have jumped directly to node `4`.

**Comment by episodeyang** [comment] 2015-10-09 06:36
Got it, I noticed that 0.12.7 is very similar to 4.0.0

So 4.0.0 is good for production? I'm too tired to think straight now.

**Comment by lpinca** [comment] 2015-10-09 06:39
node [`4.2.0`](https://github.com/nodejs/node/pull/3258) will be the first LTS release, so yes, it's safe for production.

**Comment by episodeyang** [comment] 2015-10-09 06:40
kk I will do that now.

**Comment by 3rd-Eden** [comment] 2015-10-09 07:04
Being a LTS release is also one of the reasons why I want to deprecate all previous node versions as soon as possible.

**Comment by lpinca** [comment] 2015-11-29 08:40
`engine.io@1.6.1` should fix this. If it is not the case, please post back.

**Closed by lpinca** 2015-11-29 08:40 UTC
Labels: bug, ★★
