### ISSUE TITLE
Erratic disconnections/reconnections with SSL errors

### ISSUE THREAD

**Issue by RVN-BR** [primus/primus#265] opened 2014-07-17 15:46 UTC
Hi Guys,

Maybe someone has gone through this or can help shed a light.  We are running primus with socket.io and using SSL.  We have been observing that at certain times we get many clients disconnecting at the same time.  Some of them are able to reconnect, and others never reconnect... (If they reload the app, they can reconnect, otherwise primus just stays reconnecting for ever)...

We have caught the following error on the console in chrome on several occurences in different machines accross different networks:

```
net::ERR_SSL_PROTOCOL_ERROR
Request.create
Request
XHR.request
XHR.doPoll
Polling.poll
Polling.doOpen
Transport.open
Socket.open
emit
attempt
delay
```

And sometimes it reconnects, sometimes it doesnt reconnect...  We are using HAProxy as the loadbalancer with 2 primus servers (1 active & 1 backup - also tried with 2 active).  We  can see disconnect events at the same second on the primus app log from many clients, which indicates that there is indeed a specific issue hapening at a certain point in time.  Previously we had not been registering the reconnections correctly on the client interface so we werent getting complaints, but we "fixed" this and exposed this other problem...

This issue happens both on Ajax fallback as well as Socket connections.  It appears as if maybe HAProxy is "dropping" a set of connections, or Primus is getting lost with its SSL on a bunch of connections - causing the browser to receive a wrong response and close the connections.  This is issue 1, and the second is why part of the connections come back quickly (within a few seconds) and part of them never recover...

**Comment by lpinca** [comment] 2016-06-11 06:59
Closing this as the conversation stalled and the issue is almost 2 years old.

**Closed by lpinca** 2016-06-11 06:59 UTC
Labels: discussion
